<h1>Add Password</h1>

<form method=post>
<ul>
	<li>
		<label for=label>Label:</label>
		<input id=label name=label type=text value=""/>
	</li>
	<li>
		<label for=domain>Domain:</label>
		<input id=domain name=domain type=text value=""/>
	</li>
	<li>
		<label for=username>Username:</label>
		<input id=username name=username type=text />
	</li>
	<li>
		<label for=password>Password:</label>
		<input id=password name=password type=text />
	</li>
	<li>
		<label for=notes>Notes:</label>
		<textarea id=notes name=notes></textarea>
	</li>
	<li>
		<input type=submit>
	</li>
</ul>
</form>
